#pragma once

#include "esp_err.h"

namespace stage2_repartition {

// Applies a new partition table and re-flashes GenesisOS slots from an SD card package.
//
// Package directory must contain:
// - partition-table.bin   (1 sector, generated by ESP-IDF build)
// - genesisos.bin         (GenesisOS app image to write into genesis_a/b/gold)
//
// Safety constraints enforced:
// - `stagetwo` factory app entry must remain at 0x20000 size 0x200000.
// - New table must define genesis_a, genesis_b, genesis_gold, user, python.
//
// Note: StageTwo never overwrites itself in this flow.
esp_err_t apply_from_sd(const char* package_dir);

}

